import os
from dotenv import load_dotenv

load_dotenv()

from typing import List

class Settings:
    PROJECT_NAME: str = "Trade Analyzer"
    VERSION: str = "1.0.0"
    API_V1_STR: str = "/api/v1"
    
    # Refresh Interval in seconds (e.g. 5 minutes)
    REFRESH_INTERVAL: int = 300
    
    # Groww Credentials
    GROWW_API_KEY: str = os.getenv("GROWW_API_KEY", "")
    GROWW_CLIENT_CODE: str = os.getenv("GROWW_CLIENT_CODE", "")
    GROWW_PASSWORD: str = os.getenv("GROWW_PASSWORD", "")
    GROWW_TOTP_KEY: str = os.getenv("GROWW_TOTP_KEY", "")

    # Security & Environment
    DEBUG: bool = os.getenv("DEBUG", "False").lower() == "true"
    ALLOWED_HOSTS: List[str] = os.getenv("ALLOWED_HOSTS", "*").split(",")
    CORS_ORIGINS: List[str] = os.getenv("CORS_ORIGINS", "*").split(",")

    
    # Hardcoded F&O Symbols (Futures & Options)
    # Source: NSE F&O Equity List (via nselib)
    FNO_STOCKS: List[str] = [
    # Top 25 Blue Chips (Priority for 512MB RAM Cap)
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "LT.NS", "KOTAKBANK.NS",
    "AXISBANK.NS", "HINDUNILVR.NS", "TATAMOTORS.NS", "M&M.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "BAJFINANCE.NS", "ADANIENT.NS", "NTPC.NS",
    "ONGC.NS", "POWERGRID.NS", "TATASTEEL.NS", "JSWSTEEL.NS", "COALINDIA.NS",
    # Rest of the list (Alphabetical)
    "360ONE.NS",
    "ABB.NS",
    "ABCAPITAL.NS",
    "ADANIENSOL.NS",
    "ADANIENT.NS",
    "ADANIGREEN.NS",
    "ADANIPORTS.NS",
    "ALKEM.NS",
    "AMBER.NS",
    "AMBUJACEM.NS",
    "ANGELONE.NS",
    "APLAPOLLO.NS",
    "APOLLOHOSP.NS",
    "ASHOKLEY.NS",
    "ASIANPAINT.NS",
    "ASTRAL.NS",
    "AUBANK.NS",
    "AUROPHARMA.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJAJFINSV.NS",
    "BAJFINANCE.NS",
    "BANDHANBNK.NS",
    "BANKBARODA.NS",
    "BANKINDIA.NS",
    "BDL.NS",
    "BEL.NS",
    "BHARATFORG.NS",
    "BHARTIARTL.NS",
    "BHEL.NS",
    "BIOCON.NS",
    "BLUESTARCO.NS",
    "BOSCHLTD.NS",
    "BPCL.NS",
    "BRITANNIA.NS",
    "BSE.NS",
    "CAMS.NS",
    "CANBK.NS",
    "CDSL.NS",
    "CGPOWER.NS",
    "CHOLAFIN.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "COFORGE.NS",
    "COLPAL.NS",
    "CONCOR.NS",
    "CROMPTON.NS",
    "CUMMINSIND.NS",
    "CYIENT.NS",
    "DABUR.NS",
    "DALBHARAT.NS",
    "DELHIVERY.NS",
    "DIVISLAB.NS",
    "DIXON.NS",
    "DLF.NS",
    "DMART.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "ETERNAL.NS",
    "EXIDEIND.NS",
    "FEDERALBNK.NS",
    "FORTIS.NS",
    "GAIL.NS",
    "GLENMARK.NS",
    "GMRAIRPORT.NS",
    "GODREJCP.NS",
    "GODREJPROP.NS",
    "GRASIM.NS",
    "HAL.NS",
    "HAVELLS.NS",
    "HCLTECH.NS",
    "HDFCAMC.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HEROMOTOCO.NS",
    "HFCL.NS",
    "HINDALCO.NS",
    "HINDPETRO.NS",
    "HINDUNILVR.NS",
    "HINDZINC.NS",
    "HUDCO.NS",
    "ICICIBANK.NS",
    "ICICIGI.NS",
    "ICICIPRULI.NS",
    "IDEA.NS",
    "IDFCFIRSTB.NS",
    "IEX.NS",
    "IIFL.NS",
    "INDHOTEL.NS",
    "INDIANB.NS",
    "INDIGO.NS",
    "INDUSINDBK.NS",
    "INDUSTOWER.NS",
    "INFY.NS",
    "INOXWIND.NS",
    "IOC.NS",
    "IRCTC.NS",
    "IREDA.NS",
    "IRFC.NS",
    "ITC.NS",
    "JINDALSTEL.NS",
    "JIOFIN.NS",
    "JSWENERGY.NS",
    "JSWSTEEL.NS",
    "JUBLFOOD.NS",
    "KALYANKJIL.NS",
    "KAYNES.NS",
    "KEI.NS",
    "KFINTECH.NS",
    "KOTAKBANK.NS",
    "KPITTECH.NS",
    "LAURUSLABS.NS",
    "LICHSGFIN.NS",
    "LICI.NS",
    "LODHA.NS",
    "LT.NS",
    "LTF.NS",
    "LTIM.NS",
    "LUPIN.NS",
    "M&M.NS",
    "MANAPPURAM.NS",
    "MANKIND.NS",
    "MARICO.NS",
    "MARUTI.NS",
    "MAXHEALTH.NS",
    "MAZDOCK.NS",
    "MCX.NS",
    "MFSL.NS",
    "MOTHERSON.NS",
    "MPHASIS.NS",
    "MUTHOOTFIN.NS",
    "NATIONALUM.NS",
    "NAUKRI.NS",
    "NBCC.NS",
    "NCC.NS",
    "NESTLEIND.NS",
    "NHPC.NS",
    "NMDC.NS",
    "NTPC.NS",
    "NUVAMA.NS",
    "NYKAA.NS",
    "OBEROIRLTY.NS",
    "OFSS.NS",
    "OIL.NS",
    "ONGC.NS",
    "PAGEIND.NS",
    "PATANJALI.NS",
    "PAYTM.NS",
    "PERSISTENT.NS",
    "PETRONET.NS",
    "PFC.NS",
    "PGEL.NS",
    "PHOENIXLTD.NS",
    "PIDILITIND.NS",
    "PIIND.NS",
    "PNB.NS",
    "PNBHOUSING.NS",
    "POLICYBZR.NS",
    "POLYCAB.NS",
    "POWERGRID.NS",
    "POWERINDIA.NS",
    "PPLPHARMA.NS",
    "PRESTIGE.NS",
    "RBLBANK.NS",
    "RECLTD.NS",
    "RELIANCE.NS",
    "RVNL.NS",
    "SAIL.NS",
    "SAMMAANCAP.NS",
    "SBICARD.NS",
    "SBILIFE.NS",
    "SBIN.NS",
    "SHREECEM.NS",
    "SHRIRAMFIN.NS",
    "SIEMENS.NS",
    "SOLARINDS.NS",
    "SONACOMS.NS",
    "SRF.NS",
    "SUNPHARMA.NS",
    "SUPREMEIND.NS",
    "SUZLON.NS",
    "SYNGENE.NS",
    "TATACONSUM.NS",
    "TATAELXSI.NS",
    "TATAPOWER.NS",
    "TATASTEEL.NS",
    "TATATECH.NS",
    "TCS.NS",
    "TECHM.NS",
    "TIINDIA.NS",
    "TITAGARH.NS",
    "TITAN.NS",
    "TMPV.NS",
    "TORNTPHARM.NS",
    "TORNTPOWER.NS",
    "TRENT.NS",
    "TVSMOTOR.NS",
    "ULTRACEMCO.NS",
    "UNIONBANK.NS",
    "UNITDSPR.NS",
    "UNOMINDA.NS",
    "UPL.NS",
    "VBL.NS",
    "VEDL.NS",
    "VOLTAS.NS",
    "WIPRO.NS",
    "YESBANK.NS",
    "ZYDUSLIFE.NS",
    ]

    # Sector Mapping (Simplified for F&O)
    SECTOR_MAPPING = {
        "RELIANCE.NS": "Energy",
        "TCS.NS": "IT",
        "HDFCBANK.NS": "Financials",
        "INFY.NS": "IT",
        "ICICIBANK.NS": "Financials",
        "HINDUNILVR.NS": "Consumer Goods",
        "ITC.NS": "Consumer Goods",
        "SBIN.NS": "Financials",
        "BHARTIARTL.NS": "Telecom",
        "BAJFINANCE.NS": "Financials",
        "KOTAKBANK.NS": "Financials",
        "L&T.NS": "Construction",
        "AXISBANK.NS": "Financials",
        "HCLTECH.NS": "IT",
        "ASIANPAINT.NS": "Consumer Goods",
        "MARUTI.NS": "Automobile",
        "SUNPHARMA.NS": "Pharma",
        "TITAN.NS": "Consumer Goods",
        "ULTRACEMCO.NS": "Construction",
        "WIPRO.NS": "IT",
        "ONGC.NS": "Energy",
        "NTPC.NS": "Energy",
        "POWERGRID.NS": "Energy",
        "JSWSTEEL.NS": "Metals",
        "TATASTEEL.NS": "Metals",
        "M&M.NS": "Automobile",
        "ADANIENT.NS": "Metals",
        "ADANIPORTS.NS": "Services",
        "COALINDIA.NS": "Energy",
        "BAJAJFINSV.NS": "Financials",
        "BPCL.NS": "Energy",
        "NESTLEIND.NS": "Consumer Goods",
        "TATAMOTORS.NS": "Automobile",
        "GRASIM.NS": "Construction",
        "TECHM.NS": "IT",
        "HINDALCO.NS": "Metals",
        "CIPLA.NS": "Pharma",
        "EICHERMOT.NS": "Automobile",
        "DRREDDY.NS": "Pharma",
        "BRITANNIA.NS": "Consumer Goods",
        "HEROMOTOCO.NS": "Automobile",
        "TATACONSUM.NS": "Consumer Goods",
        "DIVISLAB.NS": "Pharma",
        "APOLLOHOSP.NS": "Pharma",
        "SBILIFE.NS": "Financials",
        "HDFCLIFE.NS": "Financials",
        "UPL.NS": "Consumer Goods",
        "LICI.NS": "Financials",
        "ADANIGREEN.NS": "Energy",
        "ADANIPOWER.NS": "Energy",
        "ATGL.NS": "Energy",
        "AMBUJACEM.NS": "Construction",
        "DMART.NS": "Retail",
        "VBL.NS": "Consumer Goods",
        "ZOMATO.NS": "Tech",
        "HAL.NS": "Defence",
        "BEL.NS": "Defence",
        "JIOFIN.NS": "Financials",
        "TRENT.NS": "Retail",
        "TATASTEEL.NS": "Metals",
        "VEDL.NS": "Metals",
        "SIEMENS.NS": "Industrial",
        "ABB.NS": "Industrial",
        "PIDILITIND.NS": "Chemicals",
        "HAVELLS.NS": "Consumer Goods",
        "DABUR.NS": "Consumer Goods",
        "GODREJCP.NS": "Consumer Goods",
        "SHREECEM.NS": "Construction",
        "BPCL.NS": "Energy",
        "IOC.NS": "Energy",
        "GAIL.NS": "Energy",
        "RECLTD.NS": "Financials",
        "PFC.NS": "Financials",
        "CHOLAFIN.NS": "Financials",
        "SHRIRAMFIN.NS": "Financials",
        "BANKBARODA.NS": "Financials",
        "PNB.NS": "Financials",
        "CANBK.NS": "Financials",
        "UNIONBANK.NS": "Financials",
        "INDUSINDBK.NS": "Financials",
        "IDFCFIRSTB.NS": "Financials",
        "LTIM.NS": "IT",
        "L&T.NS": "Construction",
        "DLF.NS": "Real Estate",
        "LODHA.NS": "Real Estate",
        "GODREJPROP.NS": "Real Estate",
        "OBEROIRLTY.NS": "Real Estate",
        "PHOENIXLTD.NS": "Real Estate",
        "PRESTIGE.NS": "Real Estate",
        "BRIGADE.NS": "Real Estate",
        "SOBHA.NS": "Real Estate",
        "SIGNATURE.NS": "Real Estate",
        "SUNTECK.NS": "Real Estate",
        "MAHLIFE.NS": "Real Estate",
        "IBREALEST.NS": "Real Estate",
        "ASHIANA.NS": "Real Estate",
        "PURVA.NS": "Real Estate",
        "KOLTEPATIL.NS": "Real Estate",
        "GANESHHOU.NS": "Real Estate",
        "ARIHANTSUP.NS": "Real Estate",
        "AJMERA.NS": "Real Estate",
        "TEXINFRA.NS": "Real Estate",
        "MARATHON.NS": "Real Estate",
        "PENINLAND.NS": "Real Estate",
        "PROZONE.NS": "Real Estate",
        "VIPULLTD.NS": "Real Estate",
        "ANSALAPI.NS": "Real Estate",
        "ANSALHSG.NS": "Real Estate",
        "ARSSINFRA.NS": "Real Estate",
        "ARTEMIS.NS": "Real Estate",
        "ASHOKLEY.NS": "Automobile",
        "TVSMOTOR.NS": "Automobile",
        "BAJAJ-AUTO.NS": "Automobile",
        "BHARATFORG.NS": "Automobile",
        "BOSCHLTD.NS": "Automobile",
        "MRF.NS": "Automobile",
        "BALKRISIND.NS": "Automobile",
        "APOLLOTYRE.NS": "Automobile",
        "CEATLTD.NS": "Automobile",
        "JKTYRE.NS": "Automobile",
        "MOTHERSON.NS": "Automobile",
        "SONACOMS.NS": "Automobile",
        "TIINDIA.NS": "Automobile",
        "UNOMINDA.NS": "Automobile",
        "ENDURANCE.NS": "Automobile",
        "CRAFTSMAN.NS": "Automobile",
        "JBMA.NS": "Automobile",
        "VARROC.NS": "Automobile",
        "MINDA.NS": "Automobile",
        "GABRIEL.NS": "Automobile",
        "LUMAXIND.NS": "Automobile",
        "LUMAXTECH.NS": "Automobile",
        "PRICOLLTD.NS": "Automobile",
        "SUBROS.NS": "Automobile",
        "SUPERHOUSE.NS": "Automobile",
        "TALBROAUTO.NS": "Automobile",
        "JAYBARMARU.NS": "Automobile",
        "MUNJALAU.NS": "Automobile",
        "MUNJALSHOW.NS": "Automobile",
        "PPAP.NS": "Automobile",
        "RICOAUTO.NS": "Automobile",
        "SHARDAMOTR.NS": "Automobile",
        "SMLISUZU.NS": "Automobile",
        "WHEELS.NS": "Automobile",
        "ZFSTEERING.NS": "Automobile",
        "AUTOAXLES.NS": "Automobile",
        "BANCOINDIA.NS": "Automobile",
        "FIEMIND.NS": "Automobile",
        "GNA.NS": "Automobile",
        "IMFA.NS": "Automobile",
        "IST.NS": "Automobile",
        "JTEKTINDIA.NS": "Automobile",
        "LGBALKRISH.NS": "Automobile",
        "M&MFIN.NS": "Financials",
        "MANAPPURAM.NS": "Financials",
        "MUTHOOTFIN.NS": "Financials",
        "POONAWALLA.NS": "Financials",
        "SUNDARMFIN.NS": "Financials",
        "CHOLHLDNG.NS": "Financials",
        "ABCAPITAL.NS": "Financials",
        "L&TFH.NS": "Financials",
        "MOTILALOFS.NS": "Financials",
        "ISEC.NS": "Financials",
        "ANGELONE.NS": "Financials",
        "MCX.NS": "Financials",
        "BSE.NS": "Financials",
        "CDSL.NS": "Financials",
        "CAMS.NS": "Financials",
        "KFINTECH.NS": "Financials",
        "HDFCAMC.NS": "Financials",
        "NAM-INDIA.NS": "Financials",
        "UTIAMC.NS": "Financials",
        "ABSLAMC.NS": "Financials",
        "CRISIL.NS": "Financials",
        "ICRA.NS": "Financials",
        "CAREERP.NS": "Financials",
        "AAVAS.NS": "Financials",
        "AUBANK.NS": "Financials",
        "BANDHANBNK.NS": "Financials",
        "CUB.NS": "Financials",
        "EQUITASBNK.NS": "Financials",
        "FEDERALBNK.NS": "Financials",
        "IDFC.NS": "Financials",
        "KARURVYSYA.NS": "Financials",
        "RBLBANK.NS": "Financials",
        "SOUTHBANK.NS": "Financials",
        "UJJIVANSFB.NS": "Financials",
        "YESBANK.NS": "Financials",
        "J&KBANK.NS": "Financials",
        "MAHABANK.NS": "Financials",
        "CENTRALBK.NS": "Financials",
        "IOB.NS": "Financials",
        "UCOBANK.NS": "Financials",
        "PSB.NS": "Financials",
        "INDIANB.NS": "Financials",
        "BANKINDIA.NS": "Financials",
        "CANBK.NS": "Financials",
        "UNIONBANK.NS": "Financials",
        "PNB.NS": "Financials",
        "BOB.NS": "Financials",
        "SBIN.NS": "Financials",
    }

settings = Settings()
